import type { RcaResult, Document } from "../types";
import { getStore } from "../store";
import { llmObject, caps } from "../ai/client";
import { z } from "zod";

// ---------------------------------------------------------------------------
// Maintenance Intelligence & RCA. Gathers every record that touches an asset —
// work orders, inspections, incidents, OEM limits, emails — from across the
// corpus and reasons over them. With a provider key the whole 5-Whys chain,
// root cause and fix are generated by the LLM from the actual evidence (not
// scripted); without one, a deterministic evidence-driven skeleton is used.
// ---------------------------------------------------------------------------

function docsForEquipment(equipmentId: string): Document[] {
  const store = getStore();
  const tag = equipmentId.toUpperCase();
  return store.documents.filter((d) =>
    d.chunks.some((c) => c.entities.map((e) => e.toUpperCase()).includes(tag))
  );
}

const RcaSchema = z.object({
  problem: z.string(),
  whys: z
    .array(
      z.object({
        question: z.string(),
        answer: z.string(),
        evidence: z.array(z.string()).describe("document ids that support this step"),
      })
    )
    .min(3)
    .max(6),
  rootCause: z.string(),
  recommendation: z.string(),
  confidence: z.number().min(0).max(1),
});

export async function runRca(equipmentId: string): Promise<RcaResult | null> {
  const store = getStore();
  const eq = store.nodes.find((n) => n.id.toUpperCase() === equipmentId.toUpperCase());
  if (!eq) return null;

  const docs = docsForEquipment(equipmentId);
  const workOrders = docs.filter((d) => d.type === "WorkOrder").sort((a, b) => a.date.localeCompare(b.date));
  const inspections = docs.filter((d) => d.type === "Inspection");
  const incidents = docs.filter((d) => d.type === "Incident");
  const oem = docs.filter((d) => d.type === "OEM Manual" || d.type === "Datasheet");

  const failureModes = store.edges
    .filter((e) => e.source === eq.id && e.type === "EXHIBITS")
    .map((e) => e.target);

  const relevant = [...workOrders, ...inspections, ...incidents, ...oem];
  const connectedSources = Array.from(new Set(relevant.map((d) => d.id)));
  const validIds = new Set(connectedSources);

  // ---- LLM-driven RCA (grounded in the real records) --------------------
  if (caps().llm && relevant.length) {
    const evidence = relevant
      .map(
        (d) =>
          `[${d.id}] ${d.type} — ${d.title} (${d.date})\n` +
          d.chunks.slice(0, 4).map((c) => c.text).join(" ")
      )
      .join("\n\n")
      .slice(0, 12000);

    const out = await llmObject({
      system:
        "You are a senior reliability engineer performing a rigorous Root Cause Analysis on rotating/static plant equipment. " +
        "Use ONLY the maintenance records provided. Build a genuine 5-Whys chain that drills from symptom to true root cause. " +
        "For each step cite the supporting document ids exactly as bracketed (e.g. DOC-WO-2023-0456). " +
        "Distinguish the real root cause from the repeatedly-replaced component. Recommend a permanent corrective action.",
      prompt: `Equipment: ${eq.label}\nKnown failure modes: ${failureModes.join(", ") || "unknown"}\n\nRECORDS:\n${evidence}`,
      schema: RcaSchema,
      timeoutMs: 60000,
      thinkingBudget: 3072, // genuine multi-step causal reasoning
    });

    if (out) {
      return {
        problem: out.problem,
        equipmentId: eq.id,
        whys: out.whys.map((w) => ({
          question: w.question,
          answer: w.answer,
          evidence: w.evidence.filter((e) => validIds.has(e)),
        })),
        rootCause: out.rootCause,
        recommendation: out.recommendation,
        confidence: Math.min(0.97, Math.round(out.confidence * 100) / 100),
        connectedSources,
      };
    }
  }

  // ---- deterministic fallback (evidence-driven, no LLM) ------------------
  const primaryMode = failureModes[0] ?? "Repeated failure";
  const inspectionFinding = inspections
    .flatMap((d) => d.chunks)
    .find((c) => /misalign|offset|foul|corros|crack|wear|vibration/i.test(c.text));

  const whys = [
    {
      question: `Why has ${eq.label.split("·")[0].trim()} needed repeated intervention?`,
      answer: `${workOrders.length} work order(s) recorded${workOrders.length ? ` (${workOrders.map((w) => w.date.slice(0, 4)).join(", ")})` : ""} for ${primaryMode.toLowerCase()}.`,
      evidence: workOrders.map((w) => w.id),
    },
    {
      question: "Why did the problem recur after each repair?",
      answer: "Each intervention addressed the failed component, not the underlying cause — the same signature returned.",
      evidence: workOrders.map((w) => w.id),
    },
    {
      question: "What does inspection evidence indicate?",
      answer: inspectionFinding ? inspectionFinding.text : "Inspection points to an underlying mechanical/condition defect.",
      evidence: inspections.map((d) => d.id),
    },
    {
      question: "Why was the true cause not fixed earlier?",
      answer: "The evidence was scattered across work orders, an incident report and OEM limits that no single reviewer had assembled together.",
      evidence: [...incidents.map((d) => d.id), oem[0]?.id].filter(Boolean) as string[],
    },
  ];

  return {
    problem: `Recurring ${primaryMode} on ${eq.label.split("·")[0].trim()}`,
    equipmentId: eq.id,
    whys,
    rootCause: inspectionFinding
      ? `Underlying condition defect evidenced by inspection: ${inspectionFinding.text.slice(0, 160)}`
      : "Underlying mechanical/condition defect masked by repeated component replacement.",
    recommendation:
      "Address the root mechanical cause (alignment/grouting/condition), add condition monitoring, and enforce the current controlled procedure on restart.",
    confidence: Math.min(0.95, 0.5 + workOrders.length * 0.1 + (inspectionFinding ? 0.2 : 0) + (incidents.length ? 0.1 : 0)),
    connectedSources,
  };
}

export function rcaCandidates() {
  const store = getStore();
  return store.nodes
    .filter(
      (n) =>
        n.type === "Equipment" &&
        store.edges.some((e) => e.source === n.id && e.type === "EXHIBITS")
    )
    .map((n) => ({
      id: n.id,
      label: n.label,
      failures: store.edges
        .filter((e) => e.source === n.id && e.type === "EXHIBITS")
        .map((e) => e.target),
    }));
}
